### ISSUE TITLE
1.0 should be moved to a beta label

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/spyder-kernels-feedstock#19]
Issue:

The 1.0 package keeps getting preferred over the 0.x package.

This causes spyder to get downgraded to some weird version that didn't restrict 1.X, namely Spyder 3.2.8.

```
conda update --all
Solving environment: done

## Package Plan ##

  environment location: C:\Users\mark\Miniconda3\envs\sp


The following NEW packages will be INSTALLED:

    sqlite:         3.13.0-vc14_0 conda-forge [vc14]

The following packages will be UPDATED:

    jpeg:           9b-vc14_2     conda-forge [vc14] --> 9c-hfa6e2cd_1001     conda-forge
    libpng:         1.6.34-vc14_0 conda-forge [vc14] --> 1.6.35-h7602738_1002 conda-forge
    qt:             5.6.2-vc14_1  conda-forge [vc14] --> 5.6.2-vc14_2         conda-forge [vc14]
    spyder-kernels: 0.2.6-py_1    conda-forge --> 1.1.0-py_0           conda-forge

The following packages will be DOWNGRADED:

    spyder:         3.3.1-py36_2  conda-forge --> 3.2.8-py36_0         conda-forge
```

It seems that it should only be used with spyder 4, which is in the beta label so maybe it is appropriate to move it to the beta label until then?

**Comment by ccordoba12** [comment]
> conda update --all

That's a killer and that's why pip 10+ stopped doing it. The 1.0+ of spyder-kernels releases are perfectly fine if you don't run this command.

**Comment by hmaarrfk** [comment]
@ccordoba12 so I shouldn't ever run the `conda update --all` command?

**Comment by ccordoba12** [comment]
Well, as you can see in this case, it breaks the restrictions imposed by some packages on others. And we're not alone here: for instance, IPython has also several restrictions that can be easily broken by `conda update --all`. So my recommendation is to only run `conda update foo` when needed.

Besides, by a mistake made by the Anaconda guys, your problem is faced by Windows users in the defaults channel as well:

https://stackoverflow.com/questions/52629377/application-spyder-launch-may-have-produced-errors-windows

**Comment by hmaarrfk** [comment]
Thanks! I'm happy closing this. The user experience isn't fun though :/

**Comment by ccordoba12** [comment]
I know. Things will be normal again once we release Spyder 4, in January of next year.
